### ISSUE TITLE
Unable to import Rmarkdown files

### ISSUE THREAD

**Issue by NaikPrateek** [att/rcloud.rmd#18] opened 2016-12-06 06:27 UTC
I tried to import the Rmarkdown file which consists the basic layout of [displaying multiple columns](http://rmarkdown.rstudio.com/flexdashboard/index.html#multiple-columns), but it throws the following error in session div

![image](https://cloud.githubusercontent.com/assets/10941328/20915278/e3a06ab8-bbaa-11e6-933c-341dc4751afc.png)

**Comment by gordonwoodhull** [comment] 2017-04-19 15:04
@useless5771, could you take a look at this? I think @gaborcsardi said this was probably a dependency problem, but I have reinstalled rmarkdown and it still does not work with the linked example.

If it is a dependency problem, we need to make sure rcloud.rmd has strong enough dependencies in its `DESCRIPTION` file.

**Comment by gordonwoodhull** [comment] 2017-04-19 15:09
I am seeing the same error when exporting from RStudio. (See [the README](https://github.com/att/rcloud.rmd) for info about the RStudio add-in.)

**Comment by useless5771** [comment] 2017-04-21 13:40
I tried exporting rmd file directly from RStudio with no luck, just got the following message in the console:
> No Rmd file is open for RCloud export.
(and the file was open)

But I did manage to reproduce the error by importing the Rmd file from RCloud UI.

In RStudio console I stepped through the rcloud.rmd#importRmd function up to the moment when it requests notebook to be created. JSON is created but it is the result of rcloud.support::rcloud.create.notebook(notebook, FALSE) that is critical. To run this function from RStudio console I would have to initialize the RCloud session context object manually. Can you give me some pointers on how I could do this, please?

My guess for now is that this is knitr version issue, I have version 1.15.19 installed which is unreleased dev version apparently. I will try to downgrade knitr to last released version (1.15.1) and see if it works - there are comments in rcloud.rmd saying that it uses internal knitr API, which could have changed since the release.

Do you know which version of knitr is the last known to work with RCloud?

**Comment by useless5771** [comment] 2017-04-21 15:44
I downgraded knitr to 1.19.1 and the issue is still there.

I managed to get a hold on the result object returned by the 
> rcloud.support::rcloud.create.notebook(notebook, FALSE) 
in rcloud.rmd/import.R#importRmd

And it has validation error messges from github:

`
$ok
[1] FALSE

$content
$content$message
[1] "Validation Failed"

$content$errors
$content$errors[[1]]
$content$errors[[1]]$resource
[1] "Gist"

$content$errors[[1]]$code
[1] "missing_field"

$content$errors[[1]]$field
[1] "files"
`
The notebook passed in is a list representing json structure of gist created from Rmd file and it looks correct. 

I also tried invoking lower level function with very basing json input: 
`
res <- gist:::create.gist("{\"files\": { \"file.R\" : {\"content\": \"My content\"}
}}", ctx = myctx) 
`
and it got executed successfully, so there seems to be something wrong in-between: conversion from list to JSON, encoding?

**Comment by gordonwoodhull** [comment] 2017-04-21 16:06
Interesting, I had suspected that something was subtly wrong with the notebook format. It's a very simple format but I think it is only defined by example [in the documentation](https://developer.github.com/v3/gists/) - it's quite possible we're getting something wrong.

I don't think `importRmd` can be run directly from RStudio (or we didn't intend it to be used that way) - the RStudio add-on should spawn another page which posts the content using purely restful calls. (It would be awesome not to need that page, but we couldn't see another way.)

**Comment by useless5771** [comment] 2017-04-21 16:44
I think I found the root cause: github rejects requests which try to create a new gist with any of the files being empty (or blank). This means that when Rmd is converted to notebook representation (in rmdToJson function) the empty files would have to be processed in special way... 
We could simply remove the empty files from the 'files' sub-list or we could set the contents of such empty files to an empty comment (specific to format of the file - based on the file extension).

**Comment by gordonwoodhull** [comment] 2017-04-21 17:00
Ah yes, we've run into that before. That's why e.g. `scratch.R` already contains a comment on a blank notebook. Also we don't persist empty cells (they are client-side only).

Not sure what we should do here - it will be lossy either way. Maybe for now we should add a comment for R cells and something appropriately blank for markdown cells. I think an empty cell can still have layout meaning in flexdashboard.

**Comment by gordonwoodhull** [comment] 2017-04-24 20:03
fixed by #22

**Closed by gordonwoodhull** 2017-04-24 20:03 UTC
